# Generated by Django 3.1.4 on 2021-01-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='important',
            new_name='is_important',
        ),
    ]
